version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: task-manager-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Optional: Nest app container if you want to dockerize backend
  # task-manager:
  #   build: .
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     DB_DATABASE: task_manager_db

volumes:
  pgdata:
